### ISSUE TITLE
Error on tests: Cannot unload plugin `odm_theme`

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_theme#114]
```
........E

======================================================================

ERROR: test suite for <class 'test_odm_theme.TestOdmThemePlugin'>

----------------------------------------------------------------------

Traceback (most recent call last):

File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/nose/suite.py", line 228, in run

self.tearDown()

File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/nose/suite.py", line 351, in tearDown

self.teardownContext(ancestor)

File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/nose/suite.py", line 367, in teardownContext

try_run(context, names)

File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/nose/util.py", line 470, in try_run

return func()

File "/usr/lib/ckan/default/src/ckanext-odm_theme/ckanext/odm_theme/tests/test_odm_theme.py", line 66, in teardown_class

self._unloadPlugin()

File "/usr/lib/ckan/default/src/ckanext-odm_theme/ckanext/odm_theme/tests/test_odm_theme.py", line 103, in _unloadPlugin

p.unload('odm_theme')

File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 198, in unload

raise Exception('Cannot unload plugin `%s`' % plugin)

Exception: Cannot unload plugin `odm_theme`

-------------------- >> begin captured logging << --------------------

test_odm_theme: DEBUG: teardown_class

--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------

Ran 8 tests in 78.774s
```

**Comment by acorbi** [comment]
Fixed via 407e14fb36bf45183f0f70f31953b9d43be8ca45
